### PR TITLE
Addition of "Author" and "Published At" features and addition of comments.

### PR DESCRIPTION
**Pull request by Moin-Memon**

### CODE REVIEW

**Comment by Moin-Memon** [comment]
This is an update to V1 implementation of previous PR. The previous PR focuses on V2 implementation so the V1 implementation has not been worked upon in that PR. Hence, I very strongly suggest to checkout the previous PR first and merge it because merging this one first and that one second will be of no utility.

**Comment by Moin-Memon** [comment]
Also, After the previous PR's merging, if any merge conflicts remain, please leave it as it is. I will very swiftly clear those.

**Comment by Moin-Memon** [comment]
image
image

**Comment by aribis369** [comment]
@rabitex Nice work.

**Pull request merged**
