### PR TITLE
ASCII Logo updated #7

### PR DESCRIPTION
**Pull request by shivam-k**
A better ASCII logo for the repository has been updated.

### CODE REVIEW

**Comment by aribis369** [comment]
@shivam-k Nice work. can you make the line "whats in the new?" a bit larger or use ASCII upon it too.

**Comment by shivam-k** [comment]
@aribis369, Thanks for your reply :) I will make changes really soon.

**Comment by aribis369** [comment]
@shivam-k Nice work.

**Comment by aribis369** [comment]
Merged.

**Comment by shivam-k** [comment]
@aribis369 I tried different ASCII effects on that, but didn't look good and readable. I think this looks classy and readable too. The ASCII I have used on "GEEK" won't fit on "Whats in the news?" due insufficient area.

**Pull request merged**
