### PR TITLE
More Features added in Sources Function.

### PR DESCRIPTION
**Pull request by Moin-Memon**

### CODE REVIEW

**Comment by Moin-Memon** [comment]
Checkout the previous PR first!.

**Comment by aribis369** [comment]
@rabitex Can you elaborate more on your new features.

**Comment by Moin-Memon** [comment]
sure

**Comment by Moin-Memon** [comment]
what my initial pr does is.....it tells you all the sources you are
referring to scrape out your news from.
This is an original feature from News Api V1.
I just brought it to this project.

On Dec 18, 2017 7:48 PM, "Moin Memon" <mmmoinronaldo@gmail.com> wrote:

sure

**Comment by Moin-Memon** [comment]
2nd PR tells you more details and URL and other info. about the source you
want to know about....once you input its index. Index is its no
 in the left of the source name in the sources list.

**Comment by Moin-Memon** [comment]
You should try it once. Its works fine and is very helpful and original. I
can send you the screenshots of the same.

**Comment by aribis369** [comment]
@rabitex Screenshots would be nice.

**Comment by Moin-Memon** [comment]
image

**Comment by Moin-Memon** [comment]
image

**Comment by Moin-Memon** [comment]
image

**Comment by Moin-Memon** [comment]
Upon pressing -1... We return to the main-menu.

**Comment by Moin-Memon** [comment]
I sent screen shots for PR#1 too. Check it out first. It has the initial commits and everything. Without modification.

**Comment by aribis369** [comment]
@rabitex I think your PR#2 depended on your PR#1, correct me if I'm wrong. Now I have merged your PR#1 so you have got merge conflicts. One thing can be done that you resolve merge conflicts or I'll revert the PR#1 merge and just merge the PR#2. Another thing keep in mind that when working on a particular domain donot make different branches, work on same branch, the changes pile up and you don't have different PRs.

**Comment by Moin-Memon** [comment]
Okay. I am learning. I ll Just solve the conflicts instantly as I have the code in my laptop. 2 mins.

**Comment by Moin-Memon** [comment]
Wait! I have my V2 file on a whole different branch as well. Will it create merge conflicts.

**Comment by Moin-Memon** [comment]
Okay. Ill check it when I send the PR and also clear any conflicts if they occur.

**Comment by aribis369** [comment]
@rabitex Good you did it.

**Pull request merged**
