### PR TITLE
News Feed More personalised and Check added for the API Key. 

### PR DESCRIPTION
**Pull request by Moin-Memon**
No need to open user-api.txt for changing the API.

### CODE REVIEW

**Comment by Moin-Memon** [comment]
Exploring and adding more v1 features.

**Comment by Moin-Memon** [comment]
Hey Aribis! Can you please give feedbacks on this PR so that I can improve and hence work on more. Thank You.

**Comment by aribis369** [comment]
@rabitex Nice work.

**Comment by aribis369** [comment]
Merged.

**Comment by Moin-Memon** [comment]
Hey I did some more work. Please wait for the PR.

**Pull request merged**
