### PR TITLE
Requirements fix

### PR DESCRIPTION
**Pull request by SubhrajitPrusty**
Added requirements.txt, updated README accordingly.

### CODE REVIEW

**Comment by aribis369** [comment]
@SubhrajitPrusty Can you add a gif of demo of the CLI in the README.
One README you can refer is [https://github.com/sipah00/CrickFev/blob/master/README.md](url)

**Comment by SubhrajitPrusty** [comment]
Sure! I'll look into it

**Comment by SubhrajitPrusty** [comment]
@aribis369 I cannot get an API key from newsapi.org The reCAPTCHA is broken.

**Comment by SubhrajitPrusty** [comment]
NVM it worked after the 30th time.

**Comment by SubhrajitPrusty** [comment]
@aribis369 Added a gif. Please review.

**Comment by aribis369** [comment]
@SubhrajitPrusty Nice work.

**Comment by aribis369** [comment]
Merged.

**Comment by aribis369** [comment]
@SubhrajitPrusty Can you update the GIF in the README for the new version of our program. Our new program has new logo and improvements, so update of README is important.

**Comment by SubhrajitPrusty** [comment]
Sure, I'll look into it.

**Pull request merged**
